//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.12 at 07:43:10 PM CET
//


package de.uni_tuebingen.qbic.guseWorkflowBeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="inh" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "execute")
public class Execute {

  @XmlAttribute(name = "desc", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String desc;
  @XmlAttribute(name = "inh", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String inh;
  @XmlAttribute(name = "key", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "NCName")
  protected String key;
  @XmlAttribute(name = "label", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String label;
  @XmlAttribute(name = "value", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String value;

  /**
   * Gets the value of the desc property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDesc() {
    return desc;
  }

  /**
   * Sets the value of the desc property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDesc(String value) {
    this.desc = value;
  }

  /**
   * Gets the value of the inh property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getInh() {
    return inh;
  }

  /**
   * Sets the value of the inh property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setInh(String value) {
    this.inh = value;
  }

  /**
   * Gets the value of the key property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getKey() {
    return key;
  }

  /**
   * Sets the value of the key property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setKey(String value) {
    this.key = value;
  }

  /**
   * Gets the value of the label property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getLabel() {
    return label;
  }

  /**
   * Sets the value of the label property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setLabel(String value) {
    this.label = value;
  }

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setValue(String value) {
    this.value = value;
  }

}
