//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.12 at 07:43:10 PM CET
//


package de.uni_tuebingen.qbic.guseWorkflowBeans;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="mdyid" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="nvalue" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ovalue" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="port" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="tim" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="user" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "history")
public class History {

  @XmlAttribute(name = "mdyid", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "NCName")
  protected String mdyid;
  @XmlAttribute(name = "nvalue", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String nvalue;
  @XmlAttribute(name = "ovalue", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String ovalue;
  @XmlAttribute(name = "port", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "NMTOKEN")
  protected String port;
  @XmlAttribute(name = "tim", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "NMTOKEN")
  protected String tim;
  @XmlAttribute(name = "user", required = true)
  protected BigInteger user;

  /**
   * Gets the value of the mdyid property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getMdyid() {
    return mdyid;
  }

  /**
   * Sets the value of the mdyid property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setMdyid(String value) {
    this.mdyid = value;
  }

  /**
   * Gets the value of the nvalue property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getNvalue() {
    return nvalue;
  }

  /**
   * Sets the value of the nvalue property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setNvalue(String value) {
    this.nvalue = value;
  }

  /**
   * Gets the value of the ovalue property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOvalue() {
    return ovalue;
  }

  /**
   * Sets the value of the ovalue property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setOvalue(String value) {
    this.ovalue = value;
  }

  /**
   * Gets the value of the port property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPort() {
    return port;
  }

  /**
   * Sets the value of the port property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setPort(String value) {
    this.port = value;
  }

  /**
   * Gets the value of the tim property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTim() {
    return tim;
  }

  /**
   * Sets the value of the tim property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTim(String value) {
    this.tim = value;
  }

  /**
   * Gets the value of the user property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getUser() {
    return user;
  }

  /**
   * Sets the value of the user property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setUser(BigInteger value) {
    this.user = value;
  }

}
