//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.12 at 07:43:10 PM CET
//


package de.uni_tuebingen.qbic.guseWorkflowBeans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: generated
   * 
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link Workflow }
   * 
   */
  public Workflow createWorkflow() {
    return new Workflow();
  }

  /**
   * Create an instance of {@link Execute }
   * 
   */
  public Execute createExecute() {
    return new Execute();
  }

  /**
   * Create an instance of {@link Output }
   * 
   */
  public Output createOutput() {
    return new Output();
  }

  /**
   * Create an instance of {@link Graf }
   * 
   */
  public Graf createGraf() {
    return new Graf();
  }

  /**
   * Create an instance of {@link Job }
   * 
   */
  public Job createJob() {
    return new Job();
  }

  /**
   * Create an instance of {@link Real }
   * 
   */
  public Real createReal() {
    return new Real();
  }

  /**
   * Create an instance of {@link Description }
   * 
   */
  public Description createDescription() {
    return new Description();
  }

  /**
   * Create an instance of {@link Input }
   * 
   */
  public Input createInput() {
    return new Input();
  }

  /**
   * Create an instance of {@link Abst }
   * 
   */
  public Abst createAbst() {
    return new Abst();
  }

  /**
   * Create an instance of {@link History }
   * 
   */
  public History createHistory() {
    return new History();
  }

  /**
   * Create an instance of {@link PortProp }
   * 
   */
  public PortProp createPortProp() {
    return new PortProp();
  }

}
